WELCOM TO MODULE FORM!

<?php
$form = $this->form;
$fullname = $form->get('fullname');
$form->prepare();
?>
<div class="row">
    <div class="col">
        <div class="col-md-6 col-sm-6 col-md-6 col-lg-6 col-md-offset-3">
            <?= $this->form()->openTag($form); //<form> 
            ?>
            <?= $this->formRow($fullname); ?>
            <?= $this->form()->closeTag($form); //</form>
            ?>
        </div>
    </div>
</div>