WELCOM TO MODULE FORM!

<?php
$form = $this->form;
$fullname = $form->get('fullname');
$hidden = $form->get('hidden');
$age = $form->get('number');
$email = $form->get('email');
$password = $form->get('password');
$gender = $form->get('gender');
$select = $form->get('select');
$textarea = $form->get('message');
$file = $form->get('file');
$checkbox = $form->get('checkbox');
$form->prepare();
?>
<div class="row">
    <div class="col">
        <div class="col-md-6 col-sm-6 col-md-6 col-lg-6 col-md-offset-3">
            <?= $this->form()->openTag($form); //<form> 
            ?>
            <?= $this->formRow($fullname); ?>
            <?= $this->formRow($hidden); ?>
            <?= $this->formRow($age); ?>
            <?= $this->formRow($email); ?>
            <?= $this->formRow($password); ?>
            <?= $this->formRow($gender); ?>
            <?= $this->formRow($select); ?>
            <?= $this->formRow($textarea); ?>
            <?= $this->formRow($file); ?>
            <?= $this->formRow($checkbox); ?>
            <?= $this->form()->closeTag($form); //</form>
            ?>
        </div>
    </div>
</div>